name: CR
version: 1.1.6
main: com.github.lukevers.CR.ChatRooms
description: Adds chat rooms!
authors: [Luke Evers, Dylan Whichard, Sasha Crofter]

commands:
    cr:
        description: creates/sets your current chat room
        usage: /cr <room>
    cr help:
        description: shows the help menu
        usage: /cr help
        aliases: cr h
    cr color:
        description: shows the colors allowed for your name, and allows you to set it
        usage: /cr color <colors>
    cr list:
        description: lists current chatrooms in use
        usage: /cr list
        aliases: cr ls
    cr banned:
        description: lists the banned colors
        usage: /cr banned
        aliases: cr ban
    cr version:
        description: shows the current version
        usage: /cr version
        aliases: cr v
    cr private:
        description: allows players to create private rooms
        usage: /cr private
    cr public:
        description: allows players to publicize their private chat rooms
        usage: /cr public
    cr nick:
        description: allows players to change their nickname in chatrooms
        usage: /cr nick <name>

permissions:
    CR.bancolour:
        description: Bans a certain color from chatrooms
        default: op
    CR.unbancolour:
        description: Unbans a certain color from chatrooms
        default: op
    CR.setdefault:
        description: Sets the default color for chatrooms
        default: op
    CR.publicprivate:
        description: allows the player to create public/private rooms
        default: op
    CR.nick:
        description: allows a player to use a nickname in a chatroom
        default: op